theme: minima
title: Cyril DUPONT
description: Bookmark this to keep an eye on my project updates!

author:
  name: Cyril DUPONT
  email: dupont.cyril+ghp@gmail.com

header_pages:
  - hone.md
  - about.md
  - portfolio.md
  - blog.md
